# Generated by Django 5.1.2 on 2024-10-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('content', models.TextField(verbose_name='texto')),
                ('image1', models.ImageField(upload_to='', verbose_name='imagen1')),
                ('image2', models.ImageField(upload_to='', verbose_name='imagen2')),
                ('image3', models.ImageField(upload_to='', verbose_name='imagen3')),
            ],
        ),
    ]
