# Generated by Django 5.1.2 on 2024-11-05 03:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapi', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='readingTime',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen3'),
        ),
    ]
