# Generated by Django 5.1.2 on 2024-12-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapi', '0003_blogpost_author_blogpost_date_blogpost_readingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
